version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: recrutary-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: recrutary

volumes:
  mongo-data:
